### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive

### ISSUE THREAD

**Issue by sapkra** [Download/anylogger#14]
I got an error in this line:
https://github.com/Download/anylogger/blob/master/anylogger.js#L72

![image](https://user-images.githubusercontent.com/8087568/99350768-7010ea80-289f-11eb-9a04-ddb935759472.png)

**Comment by Download** [comment]
Can you tell me about the context in which the error occurred? How could I try to reproduce this?

**Comment by Download** [comment]
So for some background info:

Anylogger's loggers are functions that have a name. The name is the logger name:

```js
var anylogger = require('anylogger')
var log = anylogger('my:test')
typeof log == 'function' // true
log.name == 'my:test' // true
```

Creating a function with an arbitrary name from code is possible in 2 ways AFAIK:

* With `eval()` or `new Function()` (widely supported, but unsafe)
* Letting the interpreter implicitly assign the name using `{[name]: function(){}}` (only modern interpreters)

The second method does not use eval, but it's using modern language features that don't work on old browsers. So until now, anylogger has been using the first method. However it seems that this is a problem in some contexts where unsafe_eval is not allowed. I would like anylogger to work in all contexts so I prepared a new release in which I'm changing this to first try the eval method but within try..catch, then try the implicit assignment method which does not work on older browsers... hopefully we can cover most cases here because older browsers ususally also don't enforce CSP policy.

Can you try out anylogger 1.0.6 for me and let me know if it helps?

**Comment by sapkra** [comment]
The context is a mattermost plugin. The mattermist server sets http headers to restrict script sources to improve the security. The list of the allowed sources you can find in the error message.

Thank you for the fast response, i will try out your change.

**Comment by sapkra** [comment]
It seems to work fine now but I don't know if these errors are happening on localhost. I will close it for now and if I get this error again I will reopen the issue.

**Comment by Download** [comment]
@sapkra Thank you for your feedback 👍
